### ISSUE TITLE
can't load history for finished code

### ISSUE THREAD

**Issue by Royhowtohack** [RunestoneInteractive/RunestoneServer#1573] opened 2020-12-30 03:32 UTC
**What Course are you in**
Runestone Java Review course

**What Page were you on**
5.6. Writing Methods

**What is your username**
RoyHack
**Describe the bug**
Some of my students found they can't load history for the completed programming challenge. I checked myself, I found I can't load history for 5.6.2. groupwork Programming Challenge : Song with Parameters

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Additional context**

**Comment by bnmnetp** [comment] 2020-12-30 16:48
Hi Thanks for reporting this.

I did a new release over the holidays with some pretty major internal updates.  It appears that introduced a couple of new bugs that our testing framework missed.  😢 

The problem is fixed as of a few hours ago.

Unfortunately the problem was not LOADING the history, the problem was in actually SAVING the code.  So for the problems you mentioned your students code was not saved, and will have to be re-entered.

I'm going to leave this Issue open in case others run into something similar that I missed.  Hopefully not!

**Comment by Royhowtohack** [comment] 2020-12-30 23:57
thanks for your response!

**Closed** 2021-01-08 22:47 UTC
