### ISSUE TITLE
502 Bad Gateway - when editing, generating and then checking Fill In the Blank 

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1021] opened 2017-08-26 18:27 UTC
I made a new question lhs_try_fillin and added it to an assignment successfully.

Then I went to re-edit the lhs_try_fillin source.  In either case, whether I edited the code, or even when not editing the code at all, I pressed Generate HTML.  Then I pressed Check Me. I would briefly see a correct feedback response.

Then a few seconds later, I get redirected to:

![image](https://user-images.githubusercontent.com/28868409/29744048-67d00c2e-8a51-11e7-86dc-cff49072129d.png)

**Comment by bnmnetp** [comment] 2017-08-26 18:47
When you re-edited the question did you do so in the original form that you used to create the question or did you click on the question and bring up the modal editor?

**Comment by psmaker** [comment] 2017-08-26 18:49
I was using the modal editor for the re-editing of the problem.

**Comment by bnmnetp** [comment] 2017-08-26 19:28
OK, thanks.  The issue is that many of the buttons we use in the components do not have a button type assigned to them explicitly, so different browsers behave differently under different circumstances.  In this case some browsers (Safari and Chrome especially) treat the default as submit and try to submit a form rather than simply calling the javascript function.

- [ ] Need to clear the original editing form after the new question is saved.
- [ ] Need to make sure button types are assigned to "button" for all runestone component buttons.

**Closed** 2021-01-07 02:38 UTC
Labels: no-issue-activity
