### ISSUE TITLE
After all the changes that have happened, I am no longer a member of my own class. This means I cannont see the textbook. Is there a way to see the entire textbook from within my own class? I tried to add myself back into the class, but received an error. Thanks for your help.

### ISSUE THREAD

**Issue by DCGlasgow** [RunestoneInteractive/RunestoneServer#1888] opened 2022-02-01 15:27 UTC
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
Knowing the course will help us a lot

**What Page were you on**

**What is your username**

**Describe the bug**
A clear and concise description of what what you were trying to accomplish and what went wrong. Vague statements like X does not work are not helpful. Imagine if one of your students sent you an email that said, "My program doesn't work, whats wrong with it?" Could you help them with only that to go on?

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools

**Comment by bnmnetp** [comment] 2022-02-01 15:32
I cannot help you unless you give me information.  The template for bug reports is there for a reason.  There are thousands of courses and hundreds of thousands of users.  There are many possible different kinds of errors. But you haven't told me any of these things.

**Comment by bnmnetp** [comment] 2022-02-01 15:35
The most common problems following the upgrade can be solved with a couple of simple steps:

1. log out and clear your browsing history.
2. log back in again and use the Change Course option under the user menu to select your course.
3. Be aware that the URL for your course has changed -- it now includes your course name -- for example `https://runestone.academy/ns/books/published/MYCOURSENAME/index.html`

**Comment by bnmnetp** [comment] 2022-02-03 15:50
Closed as duplicate of #1884

**Closed by bnmnetp** 2022-02-03 15:50 UTC
Labels: Duplicate
