### ISSUE TITLE
Can't Access Course

### ISSUE THREAD

**Issue by ICNVentures** [RunestoneInteractive/RunestoneServer#1889] opened 2022-02-03 13:27 UTC
Logged in, from https://runestone.academy/courses, if I click on my course (ACAD-APCSA-21-22) that I've been accessing for 6 months, it takes me to https://runestone.academy/user/login, which isn't a login page, but has "About" and "How Can I Help" content.  Clicking "Back to ACAD-APCSA-21-22" stays on the same page.

SOLUTION:  Go to "Enroll in Course", don't make any changes, click "Apply Changes".  This restored access to my course.

Still would like to know: Can we pay to get an account that doesn't have pop-up ads?

**Comment by bhoffman0** [comment] 2022-02-03 14:39
Try logging out, doing a [hard refresh](https://fabricdigital.co.nz/blog/how-to-hard-refresh-your-browser-and-clear-cache) on the cache, and logging back in. This fixes this problem which was due to Runestone server changes.  Also make sure you are no longer using links with csawesome.runestone.academy. The links should just start with runestone.academy and can include your course name. 
Pop-up ads are only shown to people who are not logged in. If you are logged in, you should not be seeing any ads.

**Comment by bnmnetp** [comment] 2022-02-03 15:34
Closed as duplicate of #1884

**Closed by bnmnetp** 2022-02-03 15:34 UTC
Labels: Duplicate
