### ISSUE TITLE
Deleting a Custom Problem from assignment after adding it into assignment

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#986] opened 2017-08-06 14:54 UTC
When trying to Write a custom problem, once the problem is added to the assignment it does not seem to be deletable. (One would probably need to delete the assignment and start over.)

**Comment by bnmnetp** [comment] 2017-08-06 16:01
@bjones1  -- any idea why the delete button would not be hooked up for an author written problem?  I've put it into debug and it the remove_question function is not called for a problem that I add through the write interface.  

If I manually move the question to a different then remove_question is called, but not until????

**Comment by bnmnetp** [comment] 2017-08-06 19:36
@bjones1 :  I've pushed on this a bit more, and I have zeroed in on lines 422-426 in assignments.html  I think the problem is that on line 426 uses this line:
```
question_picker.jstree(true).uncheck_node(row['question'])
```
to delete the row.  However because this is a new question it does not exist in the picker tree.  So in this case we might need to call remove_question directly, or when we add a new question we might need to add it to the picker tree.

**Comment by psmaker** [comment] 2017-08-07 07:20
I tried your suggestion of putting in the remove_question to the assignment.html in my local build and it seemed to work. The `x` delete button worked on both picker-tree questions as well as custom questions.
```
 'click .question_table_remove': function (e, value, row, index) {
    // Unchecking the question in the tree picker also deletes it from the database and table.
    question_picker.jstree(true).uncheck_node(row['question']);
    // Delete custom question from database since line above will not remove it if not in picker tree
    // and calling it for questions in the picker tree is safe as well even if it was already deleted(?)
    remove_question(row['question']);
```

**Comment by bjones1** [comment] 2017-08-07 12:18
@bnmnetp, correct -- I assume that all questions are in the question picker when doing table operations. Either solution should work; if we add questions to the picker, should there be a category titled "User-supplied questions"? We'll also need a subcategory (questions must be children of a subchapter) -- perhaps by author name? Or, we can add a field marking this as a user-written question and simply call remove_question directly. Just let me know which approach you'd prefer and I'll be happy to work on it.

**Comment by bnmnetp** [comment] 2017-08-07 12:26
Thanks!

* I think it was assumed that user written questions would be added to the Exercises subchapter automatically -- I need to check whether we are actually enforcing that.

* So, yes when a new question is added it should be added to the table as well as the picker tree under the chapter supplied by the user with the subchapter of Exercises

**Comment by bnmnetp** [comment] 2017-08-09 20:31
@psmaker -- this appears to work well for me now.

**Closed by bnmnetp** 2017-08-09 20:31 UTC
