### ISSUE TITLE
Auto-grading exercises scoring 0 in a new assignment with old exercises

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneServer#1060] opened 2017-11-14 20:17 UTC
In our LHSIntroCS_2017 book:

Made an Assignment with lhs_9_t1_p6.
Students did that problem.
Deleted the Assignment.

Made a new Assignment that had the same lhs_9_t1_p6.
When trying to grade the new Assignment, the lhs_9_t1_p6 is auto-grading to a 0, even though the problems are correctly passing in the unit test.

We used this "flow" because we wanted to "hide" the problems again from other students in other periods. So, we deleted the assignment, thinking that we could make a new assignment that points to the old problem when we ultimately wanted to grade it.

**Comment by psmaker** [comment] 2017-11-14 20:35
One more thing if it matters...

Prior to trying this flow, I had experimented with this flow in the LHSIntroCS book. I added an assignment w/ lhs_9_t1_p6, then deleted it, then added a new assignment lhs_9_t1_p6. 

I never tried to auto-grade it...

Then seeing that the flow seemed to work in the LHSIntroCS book, I redid this flow using the same problem lhs_9_t1_p6 in the LSHIntroCS_2017 book.

**Comment by bnmnetp** [comment] 2017-11-15 02:49
I'll admit I'm very confused about this one.

I can find a QUESTION with the name lhs_9_t1_p6.  But that does not appear to be a part of ANY assignment.  Which would explain why its not autograding.  

A couple of observations/questions.

1.  deleting  a question and then making a new one with the same name is a bad idea if that question has been used in an assignment.  I'm not sure thats what you did though.

2.  Deleting assignments is definitely going to wipe out grades in the gradebook for all the problems in that assignment.  Adding them back to a different assignment later should work, but you'll need to re-grade them as the question_id, assignment_id pair will have changed.

Could you be more clear about what problem you are trying to solve with this flow?  I feel like there is a feature request in here but I'm not quite getting.

**Comment by psmaker** [comment] 2017-11-15 18:54
Yes, I'm sorry. I deleted the Assignment so that is why you could not find it...  Sorry for the confusion.

I recreated the Assignment - labelled T6. It has 2 questions: lhs_9_t1_p6 and lhs_9_t2_p7.

For example, student Christina Cui - there are two problems she did that are auto-grading to 0. It tried it with and without the deadline checkbox and it always scores as 0.

The problem I was trying to solve with this flow was to prevent other students in other periods from viewing the Assignment. (Since the test feature is not working w/o a local build, we tried to use the Assignment to create a mini-test with two questions.) During their appointed class period, we created the assignment, but then we wanted to delete it so that other students in other class periods could not see the assignment (or do the assignment) prematurely. Once all students had taken the test, we would then re-create the assignment so that we could grade it.

**Comment by psmaker** [comment] 2017-11-17 20:41
just recreated T6 again... as other teacher deleted it... sorry.

**Comment by bnmnetp** [comment] 2017-11-17 23:24
What happens when you run the assignment for that student manually?

What if you try to autograde just that question for that student?

**Comment by psmaker** [comment] 2017-11-18 01:23
If I try grading that one question for one student, it shows as 0 points auto graded. But it says that 100% of the 3 test pass when I manually run it in the Grading tab.

**Comment by psmaker** [comment] 2017-11-18 17:28
Oh, btw, I changed the name from T6 to Assignment - Unit 1 to make it a little more inconspicuous. (The due date I used is very old now, but that has not been the issue.)

**Comment by bnmnetp** [comment] 2017-12-16 13:22
I haven't been able to recreate the problem on this one.  Do you have anything more to add??

In any case, I've added a visibile attribute to the assignment interface so that you can check and uncheck a checkbox for the assignment which will either show the students the assignment or keep it hidden depending on your wishes.  I think this is what you were trying to accomplish in the first place.  So hopefully you will agree this is a good solution.

**Comment by psmaker** [comment] 2017-12-18 08:03
Although I have seen this again on another assignment, I can't find a clear repeatable sequence.

But, the feature that you are suggestion is perfect for what we were looking for - thanks!

**Comment by bnmnetp** [comment] 2018-01-25 19:44
I think we all agree that this is a duplicate of #1088 so I'm going to close this one as we are closer to a long term solution on that discussion.

**Closed by bnmnetp** 2018-01-25 19:44 UTC
